/* site-data.js */
export const TECH_LOGOS = [
  { name: "GitHub",       abbr: "GH", color: "#1F2542" },
  { name: "Flutter",      abbr: "FL", color: "#4C6EF5" },
  { name: "Python",       abbr: "PY", color: "#E8A33D" },
  { name: "Firebase",     abbr: "FB", color: "#E8A33D" },
  { name: "Figma",        abbr: "FG", color: "#4C6EF5" },
  { name: "Go",           abbr: "GO", color: "#4C6EF5" },
  { name: "React Native", abbr: "RN", color: "#4A1942" },
  { name: "Android",      abbr: "AN", color: "#1F2542" },
];

export const TECH_DETAILS = {
  GitHub:       { pct: 90,  text: "Version control, branching workflows, and CI-friendly repo hygiene." },
  Flutter:      { pct: 82,  text: "Cross-platform mobile UI with a single codebase for iOS and Android." },
  Python:       { pct: 86,  text: "Scripting, APIs, and back-end services with Django/Flask." },
  Firebase:     { pct: 100, text: "Auth, real-time database, and hosting for fast-shipping apps." },
  Figma:        { pct: 78,  text: "Translating designs into pixel-accurate, responsive interfaces." },
  Go:           { pct: 70,  text: "Lightweight, concurrent back-end services and APIs." },
  "React Native": { pct: 91, text: "Native-feeling mobile apps shared across platforms." },
  Android:      { pct: 75,  text: "Native Android fundamentals for platform-specific needs." },
};

export const STATS = [
  { value: 5,   suffix: "+", label: "Years experience" },
  { value: 30,  suffix: "+", label: "Projects completed" },
  { value: 44,  suffix: "+", label: "Happy clients" },
  { value: 100, suffix: "%", label: "Client satisfaction" },
];

export const SKILLS = [
  { name: "HTML",         pct: 95 },
  { name: "React Native", pct: 91 },
  { name: "Flutter",      pct: 82 },
  { name: "C++",          pct: 88 },
  { name: "Python",       pct: 86 },
  { name: "Firebase",     pct: 100 },
];

export const SERVICES = [
  {
    title: "Front-end development",
    text: "Building responsive, modern, and interactive user interfaces that deliver smooth and engaging user experiences.",
    tech: "HTML · CSS · JavaScript · React · Flutter",
    tone: "plum",
  },
  {
    title: "Back-end development",
    text: "Developing secure, scalable, and efficient server-side systems, APIs, and application logic.",
    tech: "Node.js · Python · REST APIs",
    tone: "navy",
  },
  {
    title: "Database development",
    text: "Designing and managing structured, scalable databases to efficiently store, organize, and retrieve application data.",
    tech: "Firebase · MySQL · PostgreSQL · MongoDB",
    tone: "clay",
  },
  {
    title: "Mobile app development",
    text: "Creating modern cross-platform mobile applications that deliver consistent experiences across different devices.",
    tech: "Flutter · Firebase · React Native · Swift",
    tone: "slate",
  },
  {
    title: "API integration",
    text: "Connecting applications with third-party services, APIs, authentication systems, and cloud platforms.",
    tech: "",
    tone: "plum",
  },
  {
    title: "System development & problem solving",
    text: "Turning complex ideas into practical, reliable, and scalable software solutions.",
    tech: "",
    tone: "navy",
  },
];

export const PROJECTS = [
  {
    id: "commerce-app",
    title: "Commerce mobile app",
    role: "Flutter · Firebase",
    tone: "plum",
    image: "",
    year: "2025",
    featured: true,
    summary: "A cross-platform storefront app with real-time inventory and checkout.",
    description: "A cross-platform storefront app built for a small retail brand, covering product browsing, cart, and checkout with real-time inventory sync. Firebase handles auth, live stock counts, and order history; the UI was built once in Flutter and shipped to both iOS and Android from a single codebase.",
    tech: ["Flutter", "Firebase", "Dart", "Stripe API"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "operations-dashboard",
    title: "Operations dashboard",
    role: "React · Node.js",
    tone: "navy",
    image: "",
    year: "2025",
    featured: true,
    summary: "An internal dashboard for tracking orders, staff, and daily metrics.",
    description: "An internal operations dashboard replacing a spreadsheet-based workflow. Staff can track orders, update statuses, and see daily performance metrics in one place. Built with a React front end and a Node.js/Express API backed by PostgreSQL, with role-based access for managers vs. staff.",
    tech: ["React", "Node.js", "Express", "PostgreSQL"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "booking-platform",
    title: "Booking platform",
    role: "React Native · MongoDB",
    tone: "amber",
    image: "",
    year: "2024",
    featured: true,
    summary: "A mobile booking flow for appointment-based service businesses.",
    description: "A booking platform for appointment-based service businesses — clients pick a service, see live availability, and book in a few taps. Built in React Native for a shared iOS/Android codebase, with a MongoDB-backed API handling scheduling logic and conflict prevention.",
    tech: ["React Native", "MongoDB", "Express"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-04",
    title: "Project 04 — add a title",
    role: "Add tech stack here",
    tone: "plum",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-05",
    title: "Project 05 — add a title",
    role: "Add tech stack here",
    tone: "navy",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-06",
    title: "Project 06 — add a title",
    role: "Add tech stack here",
    tone: "amber",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-07",
    title: "Project 07 — add a title",
    role: "Add tech stack here",
    tone: "plum",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-08",
    title: "Project 08 — add a title",
    role: "Add tech stack here",
    tone: "navy",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-09",
    title: "Project 09 — add a title",
    role: "Add tech stack here",
    tone: "amber",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-10",
    title: "Project 10 — add a title",
    role: "Add tech stack here",
    tone: "plum",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-11",
    title: "Project 11 — add a title",
    role: "Add tech stack here",
    tone: "navy",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-12",
    title: "Project 12 — add a title",
    role: "Add tech stack here",
    tone: "amber",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-13",
    title: "Project 13 — add a title",
    role: "Add tech stack here",
    tone: "plum",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-14",
    title: "Project 14 — add a title",
    role: "Add tech stack here",
    tone: "navy",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-15",
    title: "Project 15 — add a title",
    role: "Add tech stack here",
    tone: "amber",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-16",
    title: "Project 16 — add a title",
    role: "Add tech stack here",
    tone: "plum",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-17",
    title: "Project 17 — add a title",
    role: "Add tech stack here",
    tone: "navy",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-18",
    title: "Project 18 — add a title",
    role: "Add tech stack here",
    tone: "amber",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-19",
    title: "Project 19 — add a title",
    role: "Add tech stack here",
    tone: "plum",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-20",
    title: "Project 20 — add a title",
    role: "Add tech stack here",
    tone: "navy",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-21",
    title: "Project 21 — add a title",
    role: "Add tech stack here",
    tone: "amber",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-22",
    title: "Project 22 — add a title",
    role: "Add tech stack here",
    tone: "plum",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
  {
    id: "project-23",
    title: "Project 23 — add a title",
    role: "Add tech stack here",
    tone: "navy",
    image: "",
    year: "2026",
    featured: false,
    summary: "Add a one-sentence summary for the homepage card and project list.",
    description: "Add the full project description here — what it does, who it was for, and what you built.",
    tech: ["Add", "tech", "here"],
    liveUrl: "",
    repoUrl: "",
  },
];

export const WHY = [
  { title: "Problem solver", text: "I break big, ambiguous requests into clear technical steps, and I don't stop at the first solution that works — I look for the one that holds up." },
  { title: "Continuous learner", text: "Tools change fast. I keep a working list of what I'm exploring next, from new frameworks to backend patterns, so my stack never goes stale." },
  { title: "User-focused", text: "Every screen and endpoint gets built with the person on the other end in mind — fast, clear, and easy to trust." },
  { title: "Passionate builder", text: "I like shipping things that work end to end: from database schema to the pixel on screen." },
];

export const SOCIALS = [
  { label: "+256 7XX XXX XXX",      href: "tel:+2567XXXXXXXX", icon: "phone" },
  { label: "@moen.fullstack.ug",   href: "#", icon: "instagram" },
  { label: "@moen.fullstack.ug",   href: "#", icon: "twitter" },
  { label: "@moen.fullstack.ug",   href: "#", icon: "linkedin" },
  { label: "Kampala, Uganda",       href: "#", icon: "pin" },
];

export const HERO_PHRASES = [
  "A full-stack developer in Uganda",
  "Front-end craftsman",
  "Back-end engineer",
  "Mobile app builder",
];
